version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 800:800
    volumes:
      - ./static/:/static/
      - ./media/:/media/
      - /var/log/locsite/nginx/:/var/log/nginx/
      - ./deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: web
    restart: always
    depends_on:
      - postgres
    environment:
      DJANGO_SETTINGS_MODULE: "locsite.settings.base"
    command: >
      sh -c "
        ./manage.py migrate;
        ./manage.py compilemessages;
        ./manage.py collectstatic --noinput;
        gunicorn --bind=0.0.0.0:8000 --timeout=90 --workers=6 --preload locsite.wsgi:application;
      "
    volumes:
      - .:/app/loc/
      - ./static/:/static
      - ./media/:/app/loc/locsite/media/
      - /var/log/locsite:/var/log/locsite
      - cachedata:/cachec
    ports:
      - 8000:8000
    env_file:
      - .env



  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./media/:/media/
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}


volumes:
  pgdata:
  cachedata:
