# Generated by Django 4.0.3 on 2022-03-26 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('created', models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 3, 26, 20, 5, 51, 899576), verbose_name='created')),
                ('about_this_event', models.TextField(verbose_name='about this event')),
                ('activate', models.BooleanField(default=True, verbose_name='activated')),
                ('number', models.PositiveIntegerField(default=1, primary_key=True, serialize=False, verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'Home Detail',
                'verbose_name_plural': 'Homes',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 3, 26, 20, 5, 51, 899576), verbose_name='created')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('position', models.CharField(max_length=220, verbose_name='position')),
                ('image', models.ImageField(upload_to='', verbose_name='pic')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('show_in_homepage', models.BooleanField(default=False, verbose_name='show in homepage')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'unique_together': {('name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 3, 26, 20, 5, 51, 899576), verbose_name='created')),
                ('name', models.CharField(max_length=330, verbose_name='name')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo')),
                ('website_address', models.URLField(verbose_name='url')),
                ('activated_for_this_event', models.BooleanField(default=True, verbose_name='activated')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'unique_together': {('website_address', 'name')},
            },
        ),
    ]
