# Generated by Django 4.0 on 2022-03-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phonenumber',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='stu_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='university',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
