# Generated by Django 4.0.4 on 2022-05-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_add_invitation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(default='team_to_user', max_length=50),
        ),
    ]
